#!/bin/bash

docker build --tag $IMAGE_NAME:v13.8.0 --build-arg NODE_VERSION=v13.8.0 .

docker build --tag $IMAGE_NAME:v12.16.0 --build-arg NODE_VERSION=v12.16.0 .

docker build --tag $IMAGE_NAME:v11.15.0 --build-arg NODE_VERSION=v11.15.0 .

docker build --tag $IMAGE_NAME:v10.19.0 --build-arg NODE_VERSION=v10.19.0 .

docker build --tag $IMAGE_NAME:v9.11.2 --build-arg NODE_VERSION=v9.11.2 .

docker build --tag $IMAGE_NAME:v8.17.0 --build-arg NODE_VERSION=v8.17.0 .
